// examples/vue/src/App.vue
<template>
  <div id="app">
    <nav class="navbar">
      <div class="navbar-content">
        <router-link
          to="/"
          class="navbar-brand"
        >
          Auth Manager Vue Demo
        </router-link>
        <div class="navbar-nav">
          <router-link
            to="/"
            :class="{ active: $route.path === '/' }"
          >
            Home
          </router-link>
          <template v-if="isAuthenticated">
            <router-link
              to="/profile"
              :class="{ active: $route.path === '/profile' }"
            >
              Profile
            </router-link>
            <span>Hello, {{ user?.displayName || user?.email || 'User' }}</span>
            <button
              @click="handleSignOut"
              class="btn btn-danger"
            >
              Sign Out
            </button>
          </template>
          <router-link
            v-else
            to="/login"
            class="btn btn-primary"
          >
            Sign In
          </router-link>
        </div>
      </div>
    </nav>

    <main class="container">
      <router-view />
    </main>
  </div>
</template>

<script setup lang="ts">
import { useAuth } from 'capacitor-auth-manager/vue';

const { isAuthenticated, user, signOut } = useAuth();

const handleSignOut = async () => {
  try {
    await signOut();
  } catch (error) {
    console.error('Sign out error:', error);
  }
};
</script>

// examples/angular/src/app/app.component.ts
import { Component, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet, RouterLink, RouterLinkActive } from '@angular/router';
import { Subscription } from 'rxjs';
import { AuthService } from 'capacitor-auth-manager/angular';
import { AuthUser } from 'capacitor-auth-manager';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, RouterLink, RouterLinkActive],
  template: `
    <nav class="navbar">
      <div class="navbar-content">
        <a
          routerLink="/"
          class="navbar-brand"
        >
          Auth Manager Angular Demo
        </a>
        <div class="navbar-nav">
          <a
            routerLink="/"
            routerLinkActive="active"
            [routerLinkActiveOptions]="{ exact: true }"
          >
            Home
          </a>
          <ng-container *ngIf="isAuthenticated$ | async; else loginLink">
            <a
              routerLink="/profile"
              routerLinkActive="active"
            >
              Profile
            </a>
            <span
              >Hello,
              {{
                (user$ | async)?.displayName || (user$ | async)?.email || 'User'
              }}</span
            >
            <button
              (click)="signOut()"
              class="btn btn-danger"
            >
              Sign Out
            </button>
          </ng-container>
          <ng-template #loginLink>
            <a
              routerLink="/login"
              class="btn btn-primary"
            >
              Sign In
            </a>
          </ng-template>
        </div>
      </div>
    </nav>

    <main class="container">
      <router-outlet></router-outlet>
    </main>
  `,
  styles: [],
})
export class AppComponent implements OnDestroy {
  isAuthenticated$ = this.authService.isAuthenticated$;
  user$ = this.authService.user$;
  private subscription?: Subscription;

  constructor(private authService: AuthService) {}

  signOut(): void {
    this.subscription = this.authService.signOut().subscribe({
      error: (error) => console.error('Sign out error:', error),
    });
  }

  ngOnDestroy(): void {
    this.subscription?.unsubscribe();
  }
}
